---
- name: Install Clickhouse
  hosts: clickhouse

  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
    - name: Start vector service
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Install GPG-key for Clickhouse
      rpm_key:
        state: present
        key: https://repo.clickhouse.com/CLICKHOUSE-KEY.GPG

    - name: Install clickhouse packages
      ansible.builtin.dnf:
        enablerepo: clickhouse-stable
        name: "{{ item }}-{{ clickhouse_version }}"
        state: present
      with_items: "{{ clickhouse_packages }}"
      notify: Start clickhouse service
    - name: Start clickhouse service
      ansible.builtin.meta: flush_handlers
    - name: Pause
      pause:
        minutes: 1
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

    - name: Install RPMs from Vector site
      ansible.builtin.dnf:
        name: "https://packages.timber.io/vector/latest/vector-0.22.2-1.x86_64.rpm"
        state: present
        disable_gpg_check: true
      notify: Start vector service

    - name: Debug
      debug:
        msg: "proverochka"
